#!/usr/bin/env python
import sys, os

if "DO_BUILT" in os.environ:
    sys.exit(0)

sys.path.insert(0, os.path.dirname(os.environ['REDO']))
import vars, runid
rid = runid.change(os.path.join(vars.STARTDIR, vars.RUNID_FILE))
sys.stderr.write("Flushing redo cache (new runid=%d)...\n" % rid)
sys.exit(0)
