# update the local 'man' branch with pregenerated output files, for people
# who don't have pandoc (and maybe to aid in google searches or something)
redo-ifchange all
git update-ref refs/heads/man origin/man '' 2>/dev/null || true

export GIT_INDEX_FILE=gitindex.tmp
rm -f $GIT_INDEX_FILE
git add -f *.1

MSG="Autogenerated man pages for $(git describe)"
TREE=$(git write-tree --prefix=Documentation)
git show-ref refs/heads/man >/dev/null && PARENT="-p refs/heads/man"
COMMITID=$(echo "$MSG" | git commit-tree $TREE $PARENT)

git update-ref refs/heads/man $COMMITID
